### ISSUE TITLE
Add license file into the `impl` sub-crate

### ISSUE THREAD

**Issue by igor-raits** [CasualX/obfstr#12]
Sadly archive on crates.io for obfstr-impl does not contain. That is resolvable in 3 simple ways: use license-file, add a symlink in the subdirectory, copy file in the subdirectory. Not sure which one you prefer, so not sending a PR.

**Comment by CasualX** [comment]
Oh thanks for letting me know!

I rewrote the entire crate to use const fn and const generics (rewrite branch) instead of proc macros so I don't think I care that much.
