### ISSUE TITLE
obfstr 0.1.x: Support raw strings

### ISSUE THREAD

**Issue by roblabla** [CasualX/obfstr#26]
obfstr 1.x currently doesn't support raw string, e.g. the following causes a panic:

```rust
obfstr!(r"do\stuff"); // Panics
obfstr!(r#"do\stuff"#); // Panics too
```

To fix this, obfstr-impl's string_parse should probably be updated to take a TokenStream instead of a Literal, and check each token in the stream.

**Comment by CasualX** [comment]
That's unfortunate but I'm not all that interested in adding features to the 0.1.x branch other than maintaining it (eg. making it work without the bootstrap hack). This is all solved by using const fn in the 0.2.x series. It also supports using actual constants (not just literals).

The only requirements for the 0.2.x branch is `min_const_generics` (which will probably be stabilized soon-ish). I am personally in favor of just waiting for that to happen and in the meantime enjoy a bootstrap hack-free obfstr 0.1.x.
