### ISSUE TITLE
trying to obfuscate a included exe

### ISSUE THREAD

**Issue by FU3X** [CasualX/obfstr#55]
let executable= obfbytes!(include_bytes!("../../target/release/main.exe"));

this wont compile maybe could you guys add another obfbytes type that can read a file and bundle it at compile time obfuscated?

**Comment by CasualX** [comment]
This should work. Please provide the output of the Rust compiler including errors it is giving.

**Comment by FU3X** [comment]
> This should work. Please provide the output of the Rust compiler including errors it is giving.

it doesn't work, and im not home, is it okay if you try? sorry

**Comment by FU3X** [comment]
@CasualX ?

**Comment by CasualX** [comment]
I cannot help without an error sorry

**Comment by FU3X** [comment]
> I cannot help without an error sorry
> 
> 
> 
> ```rust
> 
> fn main() {
> 
> 	let f = obfstr::obfbytes!(include_bytes!("bytes.rs"));
> 
> }
> 
> ```
> 
> 
> 
> (where the source file is named bytes.rs)
> 
> 
> 
> I even padded the file to 2 MiB and it worked just fine.

ye ill be on tommorow,also isn't that basically a "FuD cRyPtEr"? 🗿, which is not my intention (it's for a image manipulation tool that i want protection for, **unrelated to the actual issue**)

**Comment by CasualX** [comment]
> isn't that basically a "FuD cRyPtEr"? 🗿

Interesting, I hadn't heard of this terminology.

The goal of obfstr is to prevent automated tools from detecting blacklisted strings/bytes. Obfstr does not attempt to prevent dedicated reverse engineers from manually figuring out the contents and it does not try to avoid looking suspicious (the obfuscated content has high entropy).

**Comment by FU3X** [comment]
@CasualX 


//use obfstr::obfbytes;
use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    let file = obfstr::obfbytes!(include_bytes!("../../target/release/main.exe"));
    let temp_dir = env::temp_dir();
    let exe_path = Path::new(&temp_dir).join("main.exe");
    fs::write(&exe_path, file).expect("Failed to write file to temp directory");
    Command::new(exe_path).spawn().expect("Failed to execute file");
}




**error msg**
  Compiling silencer_src v0.1.0 (C:\Users\fu3x1\Documents\src\viral\rust\main\silencer_src)
error[E0080]: evaluation of constant value failed
   --> C:\Users\fu3x1\.cargo\registry\src\github.com-1ecc6299db9ec823\obfstr-0.4.3\src\bytes.rs:125:15     
    |
125 |         round_key = next_round(round_key);
    |                     ^^^^^^^^^^^^^^^^^^^^^ exceeded interpreter step limit (see `#[const_eval_limit]`)
    |
note: inside `obfstr::bytes::keystream::<5144064>`
   --> C:\Users\fu3x1\.cargo\registry\src\github.com-1ecc6299db9ec823\obfstr-0.4.3\src\bytes.rs:125:15
    |
125 |         round_key = next_round(round_key);
    |                     ^^^^^^^^^^^^^^^^^^^^^
note: inside `_OBFBYTES_KEYSTREAM`
   --> src\main.rs:8:19
    |
8   |     let payload = obfstr::obfbytes!(include_bytes!("../../target/release/main.exe"));
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this error originates in the macro `$crate::__obfbytes` which comes from the expansion of the macro `obfstr::obfbytes` (in Nightly builds, run with -Z macro-backtrace for more info)

note: erroneous constant used
 --> src\main.rs:8:19
  |
8 |     let payload = obfstr::obfbytes!(include_bytes!("../../target/release/main.exe"));
  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this note originates in the macro `$crate::__obfbytes` which comes from the expansion of the macro `obfstr::obfbytes` (in Nightly builds, 
run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.

**Comment by CasualX** [comment]
Ok, you're trying to include a file of size `135104112` (almost 129 MiB) and it looks like the obfuscation (which happens at compile time) does not succeed within the evaluation limit set by Rust (it hints at `#[const_eval_limit]` to configure this limit but this option is nightly only).

Also this obfuscation library deobfuscates the result to a stack variable. 129 MiB is going to blow out the stack and crash at runtime just allocating space.

Can you confirm the binary you're including is indeed 129 MiB? That seems _huge_ for an executable. If you can't reduce its size (eg. make sure it's a release build and debuginfo isn't embedded or maybe it contains a bunch of resources?) you should be looking at a separate, custom build step as this library isn't made to support such huge files.

**Comment by FU3X** [comment]
> Ok, you're trying to include a file of size 135104112 bytes (almost 129 MiB) and it looks like the obfuscation (which happens at compile time) does not succeed within the evaluation limit set by Rust (it hints at `#[const_eval_limit]` to configure this limit but this option is nightly only).
> 
> 
> 
> Also this obfuscation library deobfuscates the result to a stack variable. 129 MiB is going to blow out the stack and crash at runtime just allocating space.
> 
> 
> 
> Can you confirm the binary you're including is indeed 129 MiB? That seems _huge_ for an executable. If you can't reduce its size (eg. make sure it's a release build and debuginfo isn't embedded or maybe it contains a bunch of resources?) you should be looking at a separate, custom build step as this library isn't made to support such huge files.

no i believe it was 6MiB, also i tried this with some random text file and it had similar output

**Comment by CasualX** [comment]
I'm going to close this as I don't think this library can help you, sorry.
